"""
Extract building facade perspective crops from downloaded Streetscape360 cube tiles.

Typical usage:
    python -m pan_tools.extract_facades --project-dir data/building_pano_random5_download
    python -m pan_tools.extract_facades --candidates data/.../facade_pano_candidates.csv --pan-dir data/.../pan_download

The script is fully offline. It reads facade/pano mappings generated by demo/shp2pan.py,
loads already-downloaded cube tiles, and writes perspective crops plus a manifest.
"""

from __future__ import annotations

import argparse
import csv
import math
from dataclasses import dataclass
from pathlib import Path

import numpy as np
from PIL import Image
from tqdm import tqdm


TILE_FACE_ORDER = ["px", "nx", "py", "ny", "pz", "nz"]
DEFAULT_GTPANOS_FACE_ORDER = "px,nx,py,ny,pz,nz"


@dataclass(frozen=True)
class CropRequest:
    row_index: int
    building_id: str
    building_cs: str
    facade_id: str
    sample_id: str
    pano_name: str
    view_azimuth: float
    facade_length: float | None
    street_distance_m: float | None
    angle_error_deg: float | None
    candidate_rank: str


def parse_float(value: str | None, default: float | None = None) -> float | None:
    if value is None or value == "":
        return default
    try:
        return float(value)
    except ValueError:
        return default


def read_requests(candidates_path: Path, only_rank: int | None, include_missing: bool) -> list[CropRequest]:
    requests: list[CropRequest] = []
    with candidates_path.open("r", encoding="utf-8-sig", newline="") as fh:
        reader = csv.DictReader(fh)
        for row_index, row in enumerate(reader, start=1):
            pano_name = (row.get("panoName") or "").strip()
            status = (row.get("download_status") or "").strip()
            rank_text = (row.get("candidate_rank") or "").strip()
            if not pano_name:
                continue
            if not include_missing and status and status not in {"found", "downloaded", "skipped"}:
                continue
            if only_rank is not None:
                rank = parse_float(rank_text)
                if rank is None or int(rank) != only_rank:
                    continue
            view_azimuth = parse_float(row.get("view_azimuth"))
            if view_azimuth is None:
                continue
            requests.append(
                CropRequest(
                    row_index=row_index,
                    building_id=(row.get("building_id") or "").strip() or "unknown_building",
                    building_cs=(row.get("building_cs") or "").strip(),
                    facade_id=(row.get("facade_id") or "").strip() or f"facade_{row_index}",
                    sample_id=(row.get("sample_id") or "").strip(),
                    pano_name=pano_name,
                    view_azimuth=view_azimuth,
                    facade_length=parse_float(row.get("facade_length")),
                    street_distance_m=parse_float(row.get("street_distance_m")),
                    angle_error_deg=parse_float(row.get("angle_error_deg")),
                    candidate_rank=rank_text,
                )
            )
    return requests


def safe_name(value: str) -> str:
    keep = []
    for ch in value:
        if ch.isalnum() or ch in {"-", "_", "."}:
            keep.append(ch)
        else:
            keep.append("_")
    return "".join(keep).strip("._") or "unnamed"


def load_image_rgb(path: Path) -> Image.Image:
    return Image.open(path).convert("RGB")


def assemble_tile_face(face_dir: Path, face: str) -> Image.Image | None:
    tile_paths = {
        (col, row): face_dir / f"{face}_{col}_{row}.jpg"
        for col in range(2)
        for row in range(2)
    }
    if not all(path.exists() for path in tile_paths.values()):
        return None

    first = load_image_rgb(tile_paths[(0, 0)])
    tile_w, tile_h = first.size
    out = Image.new("RGB", (tile_w * 2, tile_h * 2))
    out.paste(first, (0, 0))
    for col in range(2):
        for row in range(2):
            if col == 0 and row == 0:
                continue
            out.paste(load_image_rgb(tile_paths[(col, row)]), (col * tile_w, row * tile_h))
    return out


def parse_face_order(face_order: str) -> list[str]:
    faces = [part.strip() for part in face_order.split(",") if part.strip()]
    if sorted(faces) != sorted(TILE_FACE_ORDER):
        raise ValueError(f"gtpanos face order must contain exactly: {', '.join(TILE_FACE_ORDER)}")
    return faces


def load_tile_cube(pano_dir: Path) -> dict[str, Image.Image] | None:
    r2_dir = pano_dir / "r2"
    if not r2_dir.exists():
        return None
    cube = {}
    for face in TILE_FACE_ORDER:
        image = assemble_tile_face(r2_dir, face)
        if image is None:
            return None
        cube[face] = image
    return cube


def load_gtpanos_cube(pano_dir: Path, face_order: list[str]) -> dict[str, Image.Image] | None:
    tiles_dir = pano_dir / "tiles"
    if not tiles_dir.exists():
        return None
    paths = [tiles_dir / f"tile_{idx:03d}.jpg" for idx in range(24)]
    if not all(path.exists() for path in paths):
        return None

    cube = {}
    idx = 0
    for face in face_order:
        first = load_image_rgb(paths[idx])
        tile_w, tile_h = first.size
        out = Image.new("RGB", (tile_w * 2, tile_h * 2))
        for col in range(2):
            for row in range(2):
                image = first if (col == 0 and row == 0) else load_image_rgb(paths[idx])
                out.paste(image, (col * tile_w, row * tile_h))
                idx += 1
        cube[face] = out
    return cube


def load_cube(pan_dir: Path, pano_name: str, gtpanos_face_order: list[str]) -> dict[str, Image.Image] | None:
    pano_dir = pan_dir / pano_name
    cube = load_tile_cube(pano_dir)
    if cube is not None:
        return cube
    return load_gtpanos_cube(pano_dir, gtpanos_face_order)


def images_to_arrays(cube: dict[str, Image.Image]) -> dict[str, np.ndarray]:
    return {face: np.asarray(image, dtype=np.uint8) for face, image in cube.items()}


def camera_rays(width: int, height: int, yaw_deg: float, pitch_deg: float, hfov_deg: float) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    hfov = math.radians(hfov_deg)
    vfov = 2.0 * math.atan(math.tan(hfov / 2.0) * height / width)
    xs = (np.arange(width, dtype=np.float32) + 0.5) / width * 2.0 - 1.0
    ys = 1.0 - (np.arange(height, dtype=np.float32) + 0.5) / height * 2.0
    x_cam, y_cam = np.meshgrid(xs * math.tan(hfov / 2.0), ys * math.tan(vfov / 2.0))

    yaw = math.radians(yaw_deg)
    pitch = math.radians(pitch_deg)
    horizontal_forward = np.array([math.sin(yaw), 0.0, math.cos(yaw)], dtype=np.float32)
    right = np.array([math.cos(yaw), 0.0, -math.sin(yaw)], dtype=np.float32)
    world_up = np.array([0.0, 1.0, 0.0], dtype=np.float32)
    forward = horizontal_forward * math.cos(pitch) + world_up * math.sin(pitch)
    up = -horizontal_forward * math.sin(pitch) + world_up * math.cos(pitch)

    dx = forward[0] + x_cam * right[0] + y_cam * up[0]
    dy = forward[1] + x_cam * right[1] + y_cam * up[1]
    dz = forward[2] + x_cam * right[2] + y_cam * up[2]
    norm = np.sqrt(dx * dx + dy * dy + dz * dz)
    return dx / norm, dy / norm, dz / norm


def sample_face(face_img: np.ndarray, u: np.ndarray, v: np.ndarray) -> np.ndarray:
    h, w, _ = face_img.shape
    x = np.clip(((u + 1.0) * 0.5 * (w - 1)).round().astype(np.int32), 0, w - 1)
    y = np.clip(((v + 1.0) * 0.5 * (h - 1)).round().astype(np.int32), 0, h - 1)
    return face_img[y, x]


def render_perspective(
    cube_arrays: dict[str, np.ndarray],
    yaw_deg: float,
    pitch_deg: float,
    hfov_deg: float,
    width: int,
    height: int,
    yaw_offset_deg: float,
) -> Image.Image:
    dx, dy, dz = camera_rays(width, height, yaw_deg + yaw_offset_deg, pitch_deg, hfov_deg)
    ax, ay, az = np.abs(dx), np.abs(dy), np.abs(dz)
    out = np.zeros((height, width, 3), dtype=np.uint8)

    masks = {
        "px": (ax >= ay) & (ax >= az) & (dx > 0),
        "nx": (ax >= ay) & (ax >= az) & (dx <= 0),
        "py": (ay > ax) & (ay >= az) & (dy > 0),
        "ny": (ay > ax) & (ay >= az) & (dy <= 0),
        "pz": (az > ax) & (az > ay) & (dz > 0),
        "nz": (az > ax) & (az > ay) & (dz <= 0),
    }

    face_uv = {
        "px": (-dz / np.maximum(ax, 1e-8), -dy / np.maximum(ax, 1e-8)),
        "nx": (dz / np.maximum(ax, 1e-8), -dy / np.maximum(ax, 1e-8)),
        "py": (dx / np.maximum(ay, 1e-8), dz / np.maximum(ay, 1e-8)),
        "ny": (dx / np.maximum(ay, 1e-8), -dz / np.maximum(ay, 1e-8)),
        "pz": (dx / np.maximum(az, 1e-8), -dy / np.maximum(az, 1e-8)),
        "nz": (-dx / np.maximum(az, 1e-8), -dy / np.maximum(az, 1e-8)),
    }

    for face, mask in masks.items():
        if not np.any(mask):
            continue
        u, v = face_uv[face]
        sampled = sample_face(cube_arrays[face], u[mask], v[mask])
        out[mask] = sampled
    return Image.fromarray(out, mode="RGB")


def write_manifest(path: Path, rows: list[dict]) -> None:
    fields = [
        "crop_path",
        "building_id",
        "building_cs",
        "facade_id",
        "sample_id",
        "panoName",
        "view_azimuth",
        "hfov",
        "pitch",
        "yaw_offset",
        "facade_length",
        "street_distance_m",
        "angle_error_deg",
        "candidate_rank",
        "source_row",
    ]
    with path.open("w", encoding="utf-8-sig", newline="") as fh:
        writer = csv.DictWriter(fh, fieldnames=fields)
        writer.writeheader()
        for row in rows:
            writer.writerow(row)


def default_candidates(project_dir: Path) -> Path:
    return project_dir / "facade_pano_candidates.csv"


def default_pan_dir(project_dir: Path) -> Path:
    return project_dir / "pan_download"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Extract facade perspective crops from downloaded panorama cube tiles")
    parser.add_argument("--project-dir", type=Path, default=None, help="Directory containing facade_pano_candidates.csv and pan_download/")
    parser.add_argument("--candidates", type=Path, default=None, help="Path to facade_pano_candidates.csv")
    parser.add_argument("--pan-dir", type=Path, default=None, help="Directory containing downloaded pano folders")
    parser.add_argument("--output", type=Path, default=None, help="Output directory for facade crops")
    parser.add_argument("--width", type=int, default=1024)
    parser.add_argument("--height", type=int, default=768)
    parser.add_argument("--hfov", type=float, default=70.0, help="Horizontal field of view in degrees")
    parser.add_argument("--pitch", type=float, default=0.0, help="Camera pitch in degrees, positive looks upward")
    parser.add_argument("--yaw-offset", type=float, default=0.0, help="Calibration offset added to view_azimuth")
    parser.add_argument("--only-rank", type=int, default=1, help="Only crop candidate_rank N; use 0 to keep all ranks")
    parser.add_argument("--limit", type=int, default=None)
    parser.add_argument("--include-missing-status", action="store_true", help="Keep rows even if download_status is not found/downloaded/skipped")
    parser.add_argument("--gtpanos-face-order", default=DEFAULT_GTPANOS_FACE_ORDER, help="Comma-separated face order for tile_000..tile_023 groups")
    parser.add_argument("--overwrite", action="store_true")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    if args.width <= 0 or args.height <= 0:
        raise ValueError("--width and --height must be positive")
    if not 1.0 <= args.hfov < 180.0:
        raise ValueError("--hfov must be in [1, 180)")

    project_dir = args.project_dir
    if project_dir is None and (args.candidates is None or args.pan_dir is None):
        project_dir = Path("data") / "building_pano_random5_download"

    candidates_path = args.candidates or default_candidates(project_dir)
    pan_dir = args.pan_dir or default_pan_dir(project_dir)
    output_dir = args.output or ((project_dir or candidates_path.parent) / "facade_crops")
    output_dir.mkdir(parents=True, exist_ok=True)

    only_rank = None if args.only_rank == 0 else args.only_rank
    requests = read_requests(candidates_path, only_rank, args.include_missing_status)
    if args.limit is not None:
        requests = requests[: args.limit]
    print(f"[extract] requests={len(requests):,}, pan_dir={pan_dir}, output={output_dir}")

    gtpanos_face_order = parse_face_order(args.gtpanos_face_order)
    cube_cache: dict[str, dict[str, np.ndarray] | None] = {}
    manifest_rows: list[dict] = []
    skipped_missing = 0
    skipped_existing = 0

    for request in tqdm(requests, desc="extract facades", unit="crop"):
        building_dir = output_dir / safe_name(request.building_id)
        building_dir.mkdir(parents=True, exist_ok=True)
        out_name = (
            f"{safe_name(request.facade_id)}"
            f"__{safe_name(request.pano_name)}"
            f"__row{request.row_index}.jpg"
        )
        out_path = building_dir / out_name
        if out_path.exists() and not args.overwrite:
            skipped_existing += 1
        else:
            if request.pano_name not in cube_cache:
                cube = load_cube(pan_dir, request.pano_name, gtpanos_face_order)
                cube_cache[request.pano_name] = images_to_arrays(cube) if cube is not None else None
            cube_arrays = cube_cache[request.pano_name]
            if cube_arrays is None:
                skipped_missing += 1
                continue
            crop = render_perspective(
                cube_arrays,
                yaw_deg=request.view_azimuth,
                pitch_deg=args.pitch,
                hfov_deg=args.hfov,
                width=args.width,
                height=args.height,
                yaw_offset_deg=args.yaw_offset,
            )
            crop.save(out_path, quality=92)

        manifest_rows.append(
            {
                "crop_path": str(out_path.relative_to(output_dir)),
                "building_id": request.building_id,
                "building_cs": request.building_cs,
                "facade_id": request.facade_id,
                "sample_id": request.sample_id,
                "panoName": request.pano_name,
                "view_azimuth": f"{request.view_azimuth:.6f}",
                "hfov": f"{args.hfov:.6f}",
                "pitch": f"{args.pitch:.6f}",
                "yaw_offset": f"{args.yaw_offset:.6f}",
                "facade_length": "" if request.facade_length is None else f"{request.facade_length:.6f}",
                "street_distance_m": "" if request.street_distance_m is None else f"{request.street_distance_m:.6f}",
                "angle_error_deg": "" if request.angle_error_deg is None else f"{request.angle_error_deg:.6f}",
                "candidate_rank": request.candidate_rank,
                "source_row": request.row_index,
            }
        )

    write_manifest(output_dir / "manifest.csv", manifest_rows)
    print(
        "[extract] done "
        f"written_or_existing={len(manifest_rows):,}, "
        f"missing_pano={skipped_missing:,}, existing_skipped={skipped_existing:,}"
    )
    print(f"[extract] manifest={output_dir / 'manifest.csv'}")


if __name__ == "__main__":
    main()
